### ISSUE TITLE
No such module 'SCSDKCreativeKit'

### ISSUE THREAD

**Issue by IcebergRage** [Jobeso/react-native-story-share#10]
Hi,

I don't use cacaoPod.

So I download SCSDKCreativeKit v1.3.1 from https://raw.githubusercontent.com/Snapchat/snap-kit-carthage/repo/SCSDKCreativeKit.json.

I add the framework to XCODE and the path in `Frameworks Searchs Paths`
I add the Header in `Header Searchs Paths`

`Always Embed Swift Started Libraries` is `true`
and in `library search paths`
```
$(inherited)
$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)
```

I still have this error : 
`No such module 'SCSDKCreativeKit'`

Any idea ?

**Comment by Jobeso** [comment]
Hey @IcebergRage,
your steps sound reasonable to me. So my suggestion is that something with the `Frameworks Searchs Paths` or `Header Searchs Paths` might be wrong. Can you post these as well?

If they also look correct, I suggest to create a clean RN app with your setup and post it here so it's easier to find a solution.

Also a hint: When you copy the framework you should activate the checkbox `Copy items if needed`.

**Comment by robwalkerco** [comment]
@IcebergRage Did you figure this out? I'm running into the same issue and cant seem to get it working 😢

**Comment by IcebergRage** [comment]
@Jobeso I confirm  `Frameworks Searchs Paths` or `Header Searchs Paths` is good !
I will retry later and take a screenshot :)

@robwalkerco no, I didn't :( As say @Jobeso, have you also check `Frameworks Searchs Paths` or `Header Searchs Paths` ? Did you check `Copy items if needed` ?

Can you post the exactly error here please :) ?

**Comment by robwalkerco** [comment]
I've ended up forking and stripping out the snapchat bits, as I'm only really interested in Instagram anyway at the moment. 
I still had some issues building without snapchat, but adding an empty swift file to the the app in xcode seemed it fix them.
