### ISSUE TITLE
dyld: Library not loaded: @rpath/PINCache.framework/PINCache

### ISSUE THREAD

**Issue by dnosk** [Jobeso/react-native-story-share#13]
iOS Build Error: dyld: Library not loaded: @rpath/PINCache.framework/PINCache

Always Embed Swift Standard Libraries: Yes

RN: 0.60.0

dyld: Library not loaded: @rpath/PINCache.framework/PINCache
  Referenced from: .../CoreSimulator/Devices/A40B2B91-4ADC-4F66-A635-1D41BF74DB3C/data/Containers/Bundle/Application/1E385D71-8295-4922-9145-C88463C0B699/adventure.app/Frameworks/SCSDKBitmojiKit.framework/SCSDKBitmojiKit
  Reason: image not found

**Comment by dnosk** [comment]
Any idea how to get around this?

**Comment by Jobeso** [comment]
The error message states that you want to link the Bitmoji framework from Snapchat but that's not necessary for this implementation, make sure that you define the subspec in your Podfile to not include the whole Snapchat SDK.

```
pod 'SnapSDK', :subspecs => ['SCSDKCreativeKit']
```

**Comment by dnosk** [comment]
Yep, tried this as well. I think it might be an issue with the autolinking in RN 0.60.0 that makes the entire SnapSDK link, which in turn throws this error.

**Comment by mph121** [comment]
Any updates?

**Comment by aboux** [comment]
It's not working on RN 0.61 as well. too bad :(

**Comment by Jobeso** [comment]
I recently worked on upgrading all libraries to RN >0.60 support. I probably will find the time in the following days to apply it to this project as well.

**Comment by aboux** [comment]
So cool! Thank you for all !

**Comment by march213** [comment]
@Jobeso What is the status?
