### ISSUE TITLE
Import is null

### ISSUE THREAD

**Issue by matiastucci** [Jobeso/react-native-story-share#17]
I followed the instructions but after doing `import RNStoryShare from 'react-native-story-share'` if I do `console.log(RNStoryShare)` I see `null`. Any idea? thanks

**Comment by Jobeso** [comment]
This is mostly related to a linking problem. In order to point into directions you need to include more detailed info e.g. `react-native info` and if you encounter this on iOS or Android.

**Comment by matiastucci** [comment]
I'm using OS X and trying iOS.

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 3.09 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 28, 29
      Build Tools: 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.1 => 0.61.1
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**Comment by Jobeso** [comment]
Since you are using react-native > 0.59 and you are on iOS, are you implementing this with cocoapods? Then you need to check the podfile cause it could be that this module currently does not support this by default.

**Comment by matiastucci** [comment]
I did `react-native link react-native-story-share` and then followed the integration part: https://github.com/Jobeso/react-native-story-share#ios-1

Should I do something else?

**Comment by Jobeso** [comment]
You'll have to check if the `react-native link` command implements the library via Pods or directly in the xcode project. The latter is the one that works with this library.

**Comment by matiastucci** [comment]
I'm [reading](https://facebook.github.io/react-native/docs/linking-libraries-ios#step-2) that for RN to link it using pods your library should have a `podspec` file and I'm not seeing one.

> Note: If your iOS project is using CocoaPods (contains Podfile) and linked library has podspec file, then react-native link will link library using Podfile.

I'm not sure but maybe that's not the problem? I don't know much about native development. What should I try?

**Comment by matiastucci** [comment]
Any ideas? Thanks!

**Comment by bobber205** [comment]
@matiastucci There is a podspec in the ios folder but I am getting the same error even after changing the file path

**Comment by bobber205** [comment]
> Since you are using react-native > 0.59 and you are on iOS, are you implementing this with cocoapods? Then you need to check the podspec cause it could be that this module currently does not support this by default.

Do you think pod file support could be added soon? I can only get the library to compile on the latest RN release using the pod route (manual linking is strongly discouraged) . Like the OP I followed the "mostly" automatic steps and then the integration steps. After doing both of those running a project in the simulator works but the import is null.

**Comment by bobber205** [comment]
My react-native info:

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
    Memory: 26.65 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /var/folders/11/4dsnq9p12xx9s0lt7l20fbfh0000gq/T/yarn--1571268126763-0.8702380761641566/node
    Yarn: 1.19.1 - /var/folders/11/4dsnq9p12xx9s0lt7l20fbfh0000gq/T/yarn--1571268126763-0.8702380761641566/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 26, 27, 28
      Build Tools: 26.0.2, 27.0.3, 28.0.3
      System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^2.7.0 => 2.9.0
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
```

**Comment by taschik** [comment]
I am running into exactly the same issue. The Pod is getting installed:
`Installing RNStoryShare (1.0.0)` 

but when accessing it it is undefined:

`TypeError: Cannot read property 'isInstagramAvailable' of undefined`

I am running the following setup:

```
System:
    OS: macOS 10.15
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 322.33 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 26, 27, 28
      Build Tools: 23.0.1, 25.0.0, 26.0.3, 27.0.3, 28.0.1, 28.0.2, 28.0.3
      System Images: android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.8.6 => 16.9.0
    react-native: ^0.60.5 => 0.60.5
  npmGlobalPackages:
    eslint-plugin-react-native: 3.5.0
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

**Comment by bobber205** [comment]
I am thinking this is just a basic configuration and compilation issue. I've tried making modifications to the podspedc file on my forked version of the repo I am trying now but nothing has worked so far (compiles but isInstagramAvailable keeps happening). I am going to try to find a template project and see if I can just port the code over to "new" package.

**Comment by bobber205** [comment]
@taschik @matiastucci Good day gentlemen.

I decided to bite the bullet today and start from scratch and used the create-react-native-module to create a fresh valid project that supports Cocoapods.

https://yarnpkg.com/en/package/react-native-legit-story-share

Should work out of the box after you've unlinked this one and add this new one. Package name is different so don't forget to update your references. Actual functionality is identical. (No snapchat)

**Comment by taschik** [comment]
That's amazing! Thanks so much. Will try to give it a try tomorrow. Super excited about it!

**Comment by matiastucci** [comment]
cool 👏 I'll try it and let you know. Thanks!
