### ISSUE TITLE
Example project doesn't work

### ISSUE THREAD

**Issue by RominHalltari** [Jobeso/react-native-story-share#2]
Hello!
I wanted to try the example project you have included in this repository to see how the library works, but that app seems to not do anything. I just ran `yarn` and then `react-native run-android`, and it runs successfully, but when clicking the "share to instagram" button, I get an error:
![Screenshot_1555958315](https://user-images.githubusercontent.com/16745534/56518193-1cadad80-653f-11e9-8b95-40c99207a4a2.png)

Am I missing something or is this a bug?

**Comment by Jobeso** [comment]
Seems to be a bug then. Maybe it's related to missing storage write permissions. I'll check it out.

**Comment by Jobeso** [comment]
Was a permissions problem indeed. With the newest version permissions are not necessary anymore. Please checkout the example project, should work now.
