### ISSUE TITLE
RNStoryShare.isInstagramAvailable() always return 'undefined' on ios

### ISSUE THREAD

**Issue by Saehanseul** [Jobeso/react-native-story-share#21]
I used RNStoryShare.isInstagramAvailable() well for a while(a year)
but few days ago, RNStoryShare.isInstagramAvailable() not working suddenly.
It always returns 'false' on IOS.(android work fine)

How can I solve it??? anyone knows?

I use,
"react-native": "^0.59.10",
"react-native-story-share": "^0.2.0",
IOS 13

**Comment by imjihun** [comment]
Currently I am using the same version and it works fine.
Check the settings again.
ex) Adding instagram-stories value as LSApplicationQueriesSchemes key value to Info.plist

**Comment by sa2812** [comment]
I get the same problem. Even trying a simple `console.log(RNStoryShare)` returns `undefined` for me.

I'm using

react-native: 0.61.2
react-native-story-share: ^0.4.0

and also iOS 13

**Comment by kyleclegg** [comment]
I was seeing this as well. I had an issue with my linking. If you're using Cocoapods then you'll probably run into this, or if the manual linking failed at any point. I had to fork the repo and fix the podspec, and now it's working well. I'll try and PR that soon.

**Comment by Jobeso** [comment]
0.5.0 was just released, can you confirm if the problem persists?

**Comment by Jobeso** [comment]
Will close this for now, feel free to open when the problem persists.

**Comment by PrinceCarter** [comment]
I'm still getting this error. 

"react-native": "^0.71.7",
"react-native-story-share": "^0.7.0",

Ran yarn add react-native-story-share

Info.plist:

  <key>LSApplicationQueriesSchemes</key>
  <array>
    <string>twitter</string>
    <string>instagram</string>
    <string>instagram-stories</string>
  </array>

Search paths: 
$(inherited)
"${DT_TOOLCHAIN_DIR}/usr/lib/swift/${PLATFORM_NAME}"
/usr/lib/swift

Here is my console log: 

 LOG  null (console.log(RNStoryShare))
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: null is not an object (evaluating '_reactNativeStoryShare.default.isInstagramAvailable')
