### ISSUE TITLE
App stuck on splash screen

### ISSUE THREAD

**Issue by virtumonde** [Jobeso/react-native-story-share#28]
After I install the library and open the app it gets stuck at the splash screen. Any ideas?

`dyld: Library not loaded: @rpath/PINCache.framework/PINCache
  Referenced from: /Users/virtumonde/Library/Developer/CoreSimulator/Devices/73CE3322-1BC4-4F6B-AB74-3855579E99B7/data/Containers/Bundle/Application/75E4666F-CF94-4426-BE66-9A6BE05DE9BF/Basic.app/Frameworks/SCSDKBitmojiKit.framework/SCSDKBitmojiKit
  Reason: image not found
(lldb) `

**Comment by iMJumpmxn** [comment]
Same issue for me!

React Native: 0.61.5
React-Native-Story-Share: 0.4.0

**Comment by virtumonde** [comment]
> Same issue for me!
> 
> React Native: 0.61.5
> React-Native-Story-Share: 0.4.0

Same specs.

**Comment by Jobeso** [comment]
The bitmoji kit shouldn't be included or you need to follow snapchats installation guide for that.

**Comment by TimBroddin** [comment]
I think the Podspec should be:

  s.dependency "SnapSDK/SCSDKCreativeKit"

I have a fork with this change present, but I'm still testing everything: https://github.com/TimBroddin/react-native-story-share

**Comment by franznkemaka** [comment]
As @TimBroddin mentioned it definitely fixes the issue

> I think the Podspec should be:
> 
> s.dependency "SnapSDK/SCSDKCreativeKit"
> 

I recently created a PR #40 , still awaiting approval. 
Meanwhile, you can use my fork as it has the latest changes too.

**Comment by Jobeso** [comment]
0.5.0 was just released with @franznkemaka fix, thanks for the awesome work on that.
Feel free to open this issue if the problem persists.

**Comment by franznkemaka** [comment]
Thanks @Jobeso for merging

**Comment by Jobeso** [comment]
@franznkemaka Thanks for your effort here.
