### ISSUE TITLE
attributionLink property

### ISSUE THREAD

**Issue by ithustle** [Jobeso/react-native-story-share#30]
I think `attributionLink` does not work propertly.
I'm trying to do something like happens on spotify:
![Screenshot_20200211-130219](https://user-images.githubusercontent.com/5114680/74235786-135d1f80-4cd0-11ea-88ba-436c858ca837.png)

But what really happens:
![Screenshot_20200211-130211](https://user-images.githubusercontent.com/5114680/74235859-38ea2900-4cd0-11ea-92e1-e92ea04292a8.png)

Code to reproduce:
```
RNStoryShare.isInstagramAvailable()
                    .then(async isAvailable => {
                        if (isAvailable) {
                            await RNStoryShare.shareToInstagram({
                                type: RNStoryShare.BASE64,
                                attributionLink: 'https://www.mysite.com',
                                backgroundAsset: imageBase64,
                                backgroundBottomColor: '#ff2a00',
                                backgroundTopColor: '#33FF33'
                            });
                        }
                    })
                    .catch(e => console.log(e));
```

**Comment by izaa** [comment]
I am wondering this too.  However, [this page](https://developers.facebook.com/docs/instagram/sharing-to-stories)  says that 

"This feature is currently in closed beta and only available to developers who have been approved for access."

But no one says how so I request for access.

**Comment by Jobeso** [comment]
Yes, @izaa is correct. This feature is in closed beta and therefore not available to most people. Let's re-open this if something related to this module pops up.

**Comment by dpickering95** [comment]
hi @Jobeso  is the above still accurate?
