### ISSUE TITLE
[iOS, Android] How to ignore snapchat SDK on instalation?

### ISSUE THREAD

**Issue by ebellumat** [Jobeso/react-native-story-share#35]
I need to use this library because the old one of react-native-instagram-story-share is depracated, but i don't want to install the snapchat SDK in the project. The minimum API os snapchat SDK is 16, and my project uses the 19, because of this the build brokes.

Theres a way to solve this?

**Comment by Jobeso** [comment]
You can't with this library, however there are people that forked this lib and removed the snapchat part. Please refer to [this dicussion](https://github.com/Jobeso/react-native-story-share/issues/19#issuecomment-542085270).
