### ISSUE TITLE
Throws error about UIImagePNGRepresentation

### ISSUE THREAD

**Issue by gwendall** [Jobeso/react-native-story-share#37]
The build fails with the following error :

`'UIImagePNGRepresentation' has been replaced by instance method 'UIImage.pngData()'`

coming from the following lines : 

https://github.com/Jobeso/react-native-story-share/blob/ac9e0e3265dfd3590850305bbf712257e6c2fd03/ios/RNStoryShare.swift#L105

https://github.com/Jobeso/react-native-story-share/blob/ac9e0e3265dfd3590850305bbf712257e6c2fd03/ios/RNStoryShare.swift#L112

**Comment by Jobeso** [comment]
Might be a regression of #32 where this line was changed. Please change it in both occasions to the following and let me know if this fixes the problem for you.
```
= UIImage(data: decodedData)!.pngData()! as NSData
```

**Comment by gwendall** [comment]
It throws tons of other errors https://www.dropbox.com/s/dgnn35zhq1x9ijp/Screenshot%202020-05-28%2007.09.00.png?dl=0

**Comment by gwendall** [comment]
Ok so I fixed it.

1. I added an empty swift file to my project, fix here : https://github.com/mxcl/PromiseKit/issues/1059#issuecomment-493925940

2. I had another error afterwards that is due to an error in the podspec file, fix here : https://github.com/Jobeso/react-native-story-share/issues/28#issuecomment-591830083

Thanks !
