### ISSUE TITLE
how to just share link by  ins

### ISSUE THREAD

**Issue by ytt123** [Jobeso/react-native-story-share#41]

**Comment by franznkemaka** [comment]
Hi @ytt123,

I guess you want to only share a link on Instagram right?
Then [react-native-share](https://github.com/react-native-community/react-native-share) is what you actually need.


````javascript

const shareOptions = {
    title: 'Share via',
    message: 'some message',
    url: 'some share url',
    social: Share.Social.INSTAGRAM,
    filename: 'test' , // only for base64 file in Android
  };

  Share.shareSingle(shareOptions)
    .then((res) => { console.log(res) })
    .catch((err) => { err && console.log(err); });

````
borrowed from their documentation [here](https://react-native-community.github.io/react-native-share/docs/share-single).

hope that is what you wanted.

**Comment by ytt123** [comment]
I will try it. anyway,thanks.------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Franz&amp;nbsp;Nkemaka&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月20日(星期天) 晚上8:57
收件人:&nbsp;&quot;Jobeso/react-native-story-share&quot;<react-native-story-share@noreply.github.com&gt;;
抄送:&nbsp;&quot;杨涛涛&quot;<1185883606@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Jobeso/react-native-story-share] how to just share link by  ins (#41)

**Comment by franznkemaka** [comment]
You're welcome, if it works, please don't hesitate to close the issue.
